import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <header id="header">

<div>
  <nav className="navbar flex justify-end pt-4 pr-4 pl-4 pb-4 mb-5 text-2xl font-bold ">
   <ul className="list-none flex gap-5 m-0 p-0 ">
    <li><Link href="/">Home</Link></li>
    <li><Link href="/about">About</Link></li>
    <li><Link href="/contact">Contact</Link></li>
      </ul>         
     </nav>
   
</div>
</header>

        
        
        
        {children}</body>
    </html>
  );
}
